volumes:
  data:

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=penka
      - POSTGRES_USER=penka
      - POSTGRES_DB=wibbu
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
